import Head from 'next/head';
import SimpleStats from 'components/Stats/SimpleStats';
import InputHiddenLabel from 'components/Form/Input/InputHiddenLabel';
import CalendarPicker from 'components/Form/Input/CalendarPicker';

export default function Home() {
  const values = [
    { key: 'Year', value: 2022 },
    { key: 'Month', value: 9 },
    { key: 'Day', value: 16 },
    { key: 'Hour', value: 22 },
    { key: 'Minute', value: 41 },
    { key: 'Second', value: 30 },
  ];
  return (
    <div className="bg-slate-100 min-h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Header /> */}
      <div className="mx-auto max-w-4xl grid grid-cols-1 gap-4 py-10 justify-items-center">
        <h1 className="text-4xl font-bold pb-20">UTC Tools</h1>
        <div className="grid grid-cols-[1fr_auto_1fr] place-items-center w-full px-4 md:px-0">
          <div className="w-full md:w-56 justify-self-end">
            <InputHiddenLabel
              label="Hello"
              name="timestamp"
              type="text"
              id="timestamp"
              placeholder="Enter timestamp"
            />
          </div>
          <div className="px-4">OR</div>
          <div className="w-full md:w-56 justify-self-start">
            <CalendarPicker />
          </div>
        </div>
        <SimpleStats data={values} />
      </div>
    </div>
  );
}
